hello.lo: /home/dtelkar/deepak/progs/myphp/hello.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/dtelkar/deepak/progs/myphp $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/dtelkar/deepak/progs/myphp/hello.c -o hello.lo 
$(phplibdir)/hello.la: ./hello.la
	$(LIBTOOL) --mode=install cp ./hello.la $(phplibdir)

./hello.la: $(shared_objects_hello) $(HELLO_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_hello) $(HELLO_SHARED_LIBADD)

